apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "logpilot.fullname" . }}
  labels:
    {{- include "logpilot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "logpilot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include "logpilot.configMapChecksum" . }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "logpilot.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "logpilot.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/sh", "-c"]
        args: ["pip install -e /app --break-system-packages && python /app/main.py"]
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        env:
        - name: APP_VERSION
          value: {{ .Chart.AppVersion | quote }}
        - name: RETAIN_ALL_POD_LOGS
          value: {{ .Values.previousPodLogs.enabled | quote }}
        - name: MAX_LOG_RETENTION_MINUTES
          value: {{ .Values.previousPodLogs.retentionMinutes | quote }}
        - name: ALLOW_PREVIOUS_LOG_PURGE
          value: {{ .Values.previousPodLogs.allowPurge | quote }}
        - name: API_KEY
          {{- if .Values.auth.existingSecret }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.auth.existingSecret }}
              key: {{ .Values.auth.existingSecretKey }}
          {{- else }}
          value: {{ .Values.auth.apiKey | quote }}
          {{- end }}
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: LOG_LEVEL
          value: {{ .Values.logging.level | quote }}
        - name: DEBUG_APP
          value: {{ .Values.logging.debug.app | quote }}
        - name: DEBUG_KUBERNETES
          value: {{ .Values.logging.debug.kubernetes | quote }}
        - name: DEBUG_ARCHIVER
          value: {{ .Values.logging.debug.archiver | quote }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: log-viewer-config
          mountPath: /app
        - name: log-dir
          mountPath: /logs
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
      volumes:
      - name: log-viewer-config
        configMap:
          name: {{ include "logpilot.fullname" . }}-config
      - name: log-dir
        {{- if eq .Values.storage.type "persistentVolume" }}
        persistentVolumeClaim:
          claimName: {{ include "logpilot.fullname" . }}-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}